entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
  https:
    address: ":443"

providers:
  docker:
    network: "edge"
  file:
    filename: "/etc/traefik/traefik-dynamic.yaml"
    watch: true

api:
  dashboard: true